# 1. EDA

In [264]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [265]:
def dataframe_info(df: pd.DataFrame):
    """
    Generate a summary DataFrame containing metadata about the columns of the input DataFrame.

    Args:
        df (pd.DataFrame): The input DataFrame.

    Returns:
        pd.DataFrame: A summary DataFrame with the following columns:
            - Column_name: Name of each column.
            - Total records: Total number of records in each column.
            - Missing Values: Number of missing (NaN) values in each column.
            - Data type: Data type of each column.
            - Unique values: Number of unique values in each column.
    """
    df_summary = pd.DataFrame({
        'Column_name': df.columns,
        'Total records': [df[col].size for col in df.columns],
        'Missing Values': [df[col].isna().sum() for col in df.columns],
        'Data type': [df[col].dtype for col in df.columns],
        'Unique values': [df[col].nunique() for col in df.columns]
    })

    return df_summary

## 1.1 Data Import

In [ ]:
df_solar = pd.read_csv('Model/SEMS_data.csv')
df_solar.head()

,Datum,Elektrárna,Klasifikace,Kapacita(kW),PV(kWh),Prodej(kWh),Koupit(kWh),Spotřeba(kWh),Spotřebováno v domácnosti(kWh),Vlastní poměr(%),Contribution Ratio(%),Příjem(CZK)
0,01.01.2024,HFVE Zapletal Simon,Úložiště baterie,7.6,1.2,0.11,14.12,20.01,5.89,98.17,29.44,6.0
1,02.01.2024,HFVE Zapletal Simon,Úložiště baterie,7.6,1.3,0.11,6.32,12.21,5.89,98.17,48.24,6.5
2,03.01.2024,HFVE Zapletal Simon,Úložiště baterie,7.6,1.9,0.12,5.51,12.19,6.68,98.24,54.80,9.5
3,04.01.2024,HFVE Zapletal Simon,Úložiště baterie,7.6,1.8,0.15,6.13,11.78,5.65,97.41,47.96,9.0
4,05.01.2024,HFVE Zapletal Simon,Úložiště baterie,7.6,4.5,0.88,5.14,14.76,9.62,91.62,65.18,22.5

In [ ]:
df_weather = pd.read_csv('Model/weather.csv')
df_weather.head()

,Unnamed: 0,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,normal.tempmax,normal.tempmin,normal.feelslike,normal.precip,normal.humidity,normal.snowdepth,normal.windspeed,normal.windgust,normal.winddir,normal.cloudcover
0,0,2023-09-01,18.1,9.5,14.3,18.1,8.3,14.2,10.4,77.7,...,"[11.5, 19.2, 31.5]","[6.9, 10.6, 16.2]","[4.8, 19.2, 30.5]","[0.0, 7.7, 43.7]","[54.4, 78.2, 97.2]","[0.0, 0.0, 0.0]","[11.9, 21.2, 29.5]","[39.6, 55.1, 111.6]","[30.3, 182.8, 327.7]","[4.7, 62.4, 100.0]"
1,1,2023-09-02,21.3,15.0,17.7,21.3,15.0,17.7,14.2,81.1,...,"[12.3, 18.5, 23.6]","[6.3, 10.4, 14.8]","[3.0, 18.5, 23.6]","[0.0, 4.0, 24.9]","[61.4, 78.0, 96.6]","[0.0, 0.0, 0.0]","[9.4, 19.1, 29.9]","[39.6, 55.1, 75.6]","[28.5, 176.3, 288.1]","[7.4, 63.7, 99.5]"
2,2,2023-09-03,19.2,14.3,16.3,19.2,14.3,16.3,12.6,79.9,...,"[11.0, 19.5, 25.8]","[5.7, 10.4, 15.2]","[3.2, 19.5, 25.8]","[0.0, 2.7, 19.4]","[62.4, 76.6, 93.4]","[0.0, 0.0, 0.0]","[11.5, 20.9, 36.0]","[28.8, 58.3, 79.2]","[38.0, 175.5, 314.5]","[17.0, 60.1, 100.0]"
3,3,2023-09-04,18.5,11.9,14.7,18.5,11.9,14.7,9.9,73.9,...,"[11.1, 19.3, 26.3]","[6.3, 10.8, 16.2]","[2.8, 19.3, 26.3]","[0.0, 2.6, 13.5]","[65.4, 77.6, 92.8]","[0.0, 0.0, 0.0]","[10.8, 20.5, 36.7]","[39.6, 57.2, 90.0]","[43.3, 189.0, 288.3]","[8.3, 60.7, 100.0]"
4,4,2023-09-05,24.2,9.4,15.7,24.2,7.9,15.4,9.9,71.2,...,"[7.7, 19.4, 27.4]","[3.4, 10.6, 14.7]","[-3.5, 19.4, 27.2]","[0.0, 2.7, 32.1]","[66.7, 77.5, 91.3]","[0.0, 0.0, 0.0]","[9.0, 22.0, 50.4]","[43.2, 63.0, 100.8]","[33.8, 157.0, 269.7]","[21.0, 55.9, 94.3]"

In [ ]:
df_weather_forecast = pd.read_csv('Model/weather_data_forecast.csv')
df_weather_forecast.head()

,datetime,datetimeEpoch,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,sunrise,sunriseEpoch,sunset,sunsetEpoch,moonphase,conditions,description,icon,stations,source
0,2025-07-12,1752271200,20.3,13.0,16.7,20.3,13.0,16.7,12.0,75.1,...,04:55:05,1752288905,20:52:05,1752346325,0.56,"Rain, Partially cloudy",Partly cloudy throughout the day with rain.,rain,"['D4554', 'LKMT', 'LKKU', 'LZZI']",comb
1,2025-07-13,1752357600,26.2,15.4,20.5,26.2,15.4,20.5,13.2,64.2,...,04:56:07,1752375367,20:51:16,1752432676,0.59,"Rain, Partially cloudy",Partly cloudy throughout the day with late aft...,rain,NaN,fcst
2,2025-07-14,1752444000,26.7,15.6,21.5,26.7,15.6,21.5,15.7,71.4,...,04:57:09,1752461829,20:50:26,1752519026,0.63,"Rain, Partially cloudy",Partly cloudy throughout the day with storms p...,rain,NaN,fcst
3,2025-07-15,1752530400,25.3,15.7,20.3,25.3,15.7,20.3,15.2,74.0,...,04:58:14,1752548294,20:49:32,1752605372,0.66,"Rain, Partially cloudy",Becoming cloudy in the afternoon with a chance...,rain,NaN,fcst
4,2025-07-16,1752616800,19.3,12.7,16.1,19.3,12.7,16.1,11.6,75.5,...,04:59:20,1752634760,20:48:36,1752691716,0.70,"Rain, Partially cloudy",Partly cloudy throughout the day with a chance...,rain,NaN,fcst

## 1.2 Dataframe info

In [269]:
dataframe_info(df_solar)

,Column_name,Total records,Missing Values,Data type,Unique values
0,Datum,669,0,object,669
1,Elektrárna,669,0,object,1
2,Klasifikace,669,0,object,1
3,Kapacita(kW),669,0,float64,1
4,PV(kWh),669,0,float64,366
5,Prodej(kWh),669,0,float64,455
6,Koupit(kWh),669,0,float64,230
7,Spotřeba(kWh),669,0,float64,541
8,Spotřebováno v domácnosti(kWh),669,0,float64,516
9,Vlastní poměr(%),669,0,float64,576
10,Contribution Ratio(%),669,0,float64,372
11,Příjem(CZK),669,0,float64,366

In [270]:
dataframe_info(df_weather)

          Column_name  Total records  Missing Values Data type  Unique values
0          Unnamed: 0            669               0     int64            669
1            datetime            669               0    object            669
2             tempmax            669               0   float64            283
3             tempmin            669               0   float64            243
4                temp            669               0   float64            262
5        feelslikemax            669               0   float64            305
6        feelslikemin            669               0   float64            272
7           feelslike            669               0   float64            295
8                 dew            669               0   float64            251
9            humidity            669               0   float64            338
10             precip            669               0   float64            367
11        precipcover            669               0   float64             25
12         preciptype            669             255    object              3
13               snow            669               0   float64             30
14          snowdepth            669               0   float64             82
15           windgust            669               0   float64            207
16          windspeed            669               0   float64            248
17            winddir            669               0   float64            596
18           pressure            669               0   float64            298
19         cloudcover            669               0   float64            433
20         visibility            669               0   float64            323
21     solarradiation            669               0   float64            595
22        solarenergy            669               0   float64            255
23            uvindex            669               0   float64             11
24       windspeedmax            669               0   float64            248
25      windspeedmean            669               0   float64            193
26            sunrise            669               0    object            651
27             sunset            669               0    object            643
28     normal.tempmax            669               0    object            365
29     normal.tempmin            669               0    object            365
30   normal.feelslike            669               0    object            365
31      normal.precip            669               0    object            350
32    normal.humidity            669               0    object            365
33   normal.snowdepth            669               0    object            238
34   normal.windspeed            669               0    object            364
35    normal.windgust            669               0    object            335
36     normal.winddir            669               0    object            365
37  normal.cloudcover            669               0    object            365

In [271]:
dataframe_info(df_weather_forecast)

       Column_name  Total records  Missing Values Data type  Unique values
0         datetime             15               0    object             15
1    datetimeEpoch             15               0     int64             15
2          tempmax             15               0   float64             14
3          tempmin             15               0   float64             13
4             temp             15               0   float64             14
5     feelslikemax             15               0   float64             13
6     feelslikemin             15               0   float64             13
7        feelslike             15               0   float64             15
8              dew             15               0   float64             14
9         humidity             15               0   float64             15
10          precip             15               0   float64             10
11      precipprob             15               0   float64             10
12     precipcover             15               0   float64              6
13      preciptype             15               4    object              1
14            snow             15               0   float64              1
15       snowdepth             15               0   float64              1
16        windgust             15               0   float64             15
17       windspeed             15               0   float64             14
18         winddir             15               0   float64             15
19        pressure             15               0   float64             14
20      cloudcover             15               0   float64             15
21      visibility             15               0   float64              7
22  solarradiation             15               0   float64             15
23     solarenergy             15               0   float64             14
24         uvindex             15               0   float64              4
25      severerisk             15               0   float64              2
26         sunrise             15               0    object             15
27    sunriseEpoch             15               0     int64             15
28          sunset             15               0    object             15
29     sunsetEpoch             15               0     int64             15
30       moonphase             15               0   float64             15
31      conditions             15               0    object              5
32     description             15               0    object              9
33            icon             15               0    object              4
34        stations             15              14    object              1
35          source             15               0    object              2

## Visual Crossing Timeline Weather API – Přehled sloupců

### 🌀 Obecné sloupce
| Název         | Popis                                                                 |
|---------------|-----------------------------------------------------------------------|
| datetime       | Datum (a čas) ve formátu ISO‑8601.                                   |
| datetimeEpoch  | Datum/čas ve formátu UNIX epoch.                                     |
| tzoffset       | Posun časové zóny vůči UTC (v hodinách).                             |

### 🌡️ Teplotní veličiny
| Název         | Popis                                                                 |
|---------------|-----------------------------------------------------------------------|
| temp           | Průměrná (nebo aktuální) teplota.                                     |
| tempmax        | Maximální denní teplota.                                              |
| tempmin        | Minimální denní teplota.                                              |
| feelslike      | Pociťovaná teplota.                                                   |
| feelslikemax   | Maximální pociťovaná teplota.                                         |
| feelslikemin   | Minimální pociťovaná teplota.                                         |

### 💧 Vlhkost a tlak
| Název         | Popis                                                                 |
|---------------|-----------------------------------------------------------------------|
| humidity        | Relativní vlhkost vzduchu (%).                                        |
| dew             | Rosný bod.                                                           |

### 🌧️ Srážky a sníh
| Název         | Popis                                                                 |
|---------------|-----------------------------------------------------------------------|
| precip          | Množství srážek (mm nebo in).                                         |
| precipprob      | Pravděpodobnost srážek (%).                                           |
| precipcover     | Pokrytí území srážkami (%).                                           |
| snow            | Výška nového sněhu.                                                  |
| snowdepth       | Celková výška sněhu.                                                 |

### 🌬️ Vítr
| Název         | Popis                                                                 |
|---------------|-----------------------------------------------------------------------|
| windspeed       | Rychlost větru.                                                      |
| winddir         | Směr větru (ve stupních, 0 = sever).                                 |
| windgust        | Rychlost poryvu větru.                                               |
| windspeed50/80/100 | Rychlost větru ve výšce 50/80/100 m.                            |
| winddir50/80/100   | Směr větru ve výšce 50/80/100 m.                                 |

### ☁️ Atmosférické parametry
| Název         | Popis                                                                 |
|---------------|-----------------------------------------------------------------------|
| pressure         | Atmosférický tlak.                                                  |
| visibility       | Viditelnost (km nebo míle).                                         |
| cloudcover       | Pokrytí oblačnosti (%).                                             |

### ☀️ Slunce a záření
| Název         | Popis                                                                 |
|---------------|-----------------------------------------------------------------------|
| sunrise          | Čas východu slunce.                                                 |
| sunset           | Čas západu slunce.                                                  |
| moonphase        | Fáze měsíce (0 = nov, 0.5 = úplněk).                                |
| solarradiation   | Solární záření (W/m²).                                              |
| solarenergy      | Solární energie (kWh/m²).                                           |
| dniradiation, difradiation, ghiradiation, gtiradiation | Různé formy solárního záření.           |
| sunelevation, sunazimuth | Elevace a azimut slunce.                                    |

### ⚠️ Výstrahy, události, aktuální podmínky
| Název         | Popis                                                                 |
|---------------|-----------------------------------------------------------------------|
| currentConditions | Detailní objekt s aktuálním stavem počasí.                        |
| alerts             | Výstrahy (např. bouřky, povodně).                                 |
| events             | Historické meteorologické události.                              |

### 📍 Lokace a metadata
| Název         | Popis                                                                 |
|---------------|-----------------------------------------------------------------------|
| queryCost         | Počet záznamů spotřebovaných dotazem.                             |
| latitude, longitude | Zeměpisná šířka a délka.                                         |
| resolvedAddress   | Geokódovaná adresa.                                               |
| address           | Zadaný název lokace.                                              |
| timezone, tzoffset | Časová zóna a posun vůči UTC.                                   |
| stationContributions | Seznam meteorologických stanic použitých k výpočtu.            |'

In [272]:
df_weather.select_dtypes(('object', 'string')).columns

Index(['datetime', 'preciptype', 'sunrise', 'sunset', 'normal.tempmax',
       'normal.tempmin', 'normal.feelslike', 'normal.precip',
       'normal.humidity', 'normal.snowdepth', 'normal.windspeed',
       'normal.windgust', 'normal.winddir', 'normal.cloudcover'],
      dtype='object')

In [273]:
df_weather.loc[:5,df_weather.select_dtypes(('object', 'string')).columns]

,datetime,preciptype,sunrise,sunset,normal.tempmax,normal.tempmin,normal.feelslike,normal.precip,normal.humidity,normal.snowdepth,normal.windspeed,normal.windgust,normal.winddir,normal.cloudcover
0,2023-09-01,['rain'],06:03:16,19:32:17,"[11.5, 19.2, 31.5]","[6.9, 10.6, 16.2]","[4.8, 19.2, 30.5]","[0.0, 7.7, 43.7]","[54.4, 78.2, 97.2]","[0.0, 0.0, 0.0]","[11.9, 21.2, 29.5]","[39.6, 55.1, 111.6]","[30.3, 182.8, 327.7]","[4.7, 62.4, 100.0]"
1,2023-09-02,['rain'],06:04:44,19:30:12,"[12.3, 18.5, 23.6]","[6.3, 10.4, 14.8]","[3.0, 18.5, 23.6]","[0.0, 4.0, 24.9]","[61.4, 78.0, 96.6]","[0.0, 0.0, 0.0]","[9.4, 19.1, 29.9]","[39.6, 55.1, 75.6]","[28.5, 176.3, 288.1]","[7.4, 63.7, 99.5]"
2,2023-09-03,['rain'],06:06:11,19:28:06,"[11.0, 19.5, 25.8]","[5.7, 10.4, 15.2]","[3.2, 19.5, 25.8]","[0.0, 2.7, 19.4]","[62.4, 76.6, 93.4]","[0.0, 0.0, 0.0]","[11.5, 20.9, 36.0]","[28.8, 58.3, 79.2]","[38.0, 175.5, 314.5]","[17.0, 60.1, 100.0]"
3,2023-09-04,['rain'],06:07:38,19:26:00,"[11.1, 19.3, 26.3]","[6.3, 10.8, 16.2]","[2.8, 19.3, 26.3]","[0.0, 2.6, 13.5]","[65.4, 77.6, 92.8]","[0.0, 0.0, 0.0]","[10.8, 20.5, 36.7]","[39.6, 57.2, 90.0]","[43.3, 189.0, 288.3]","[8.3, 60.7, 100.0]"
4,2023-09-05,NaN,06:09:06,19:23:53,"[7.7, 19.4, 27.4]","[3.4, 10.6, 14.7]","[-3.5, 19.4, 27.2]","[0.0, 2.7, 32.1]","[66.7, 77.5, 91.3]","[0.0, 0.0, 0.0]","[9.0, 22.0, 50.4]","[43.2, 63.0, 100.8]","[33.8, 157.0, 269.7]","[21.0, 55.9, 94.3]"
5,2023-09-06,NaN,06:10:33,19:21:45,"[12.7, 18.7, 27.1]","[3.2, 9.4, 14.7]","[0.9, 18.7, 27.1]","[0.0, 5.3, 49.9]","[67.1, 78.5, 96.8]","[0.0, 0.0, 0.0]","[11.5, 20.2, 36.7]","[43.2, 56.5, 97.2]","[35.0, 178.1, 259.9]","[11.3, 56.4, 100.0]"

In [274]:
df_weather_forecast.select_dtypes(('object', 'string')).columns

Index(['datetime', 'preciptype', 'sunrise', 'sunset', 'conditions',
       'description', 'icon', 'stations', 'source'],
      dtype='object')

In [275]:
df_weather.loc[:5,df_weather.select_dtypes(('object', 'string')).columns]

,datetime,preciptype,sunrise,sunset,normal.tempmax,normal.tempmin,normal.feelslike,normal.precip,normal.humidity,normal.snowdepth,normal.windspeed,normal.windgust,normal.winddir,normal.cloudcover
0,2023-09-01,['rain'],06:03:16,19:32:17,"[11.5, 19.2, 31.5]","[6.9, 10.6, 16.2]","[4.8, 19.2, 30.5]","[0.0, 7.7, 43.7]","[54.4, 78.2, 97.2]","[0.0, 0.0, 0.0]","[11.9, 21.2, 29.5]","[39.6, 55.1, 111.6]","[30.3, 182.8, 327.7]","[4.7, 62.4, 100.0]"
1,2023-09-02,['rain'],06:04:44,19:30:12,"[12.3, 18.5, 23.6]","[6.3, 10.4, 14.8]","[3.0, 18.5, 23.6]","[0.0, 4.0, 24.9]","[61.4, 78.0, 96.6]","[0.0, 0.0, 0.0]","[9.4, 19.1, 29.9]","[39.6, 55.1, 75.6]","[28.5, 176.3, 288.1]","[7.4, 63.7, 99.5]"
2,2023-09-03,['rain'],06:06:11,19:28:06,"[11.0, 19.5, 25.8]","[5.7, 10.4, 15.2]","[3.2, 19.5, 25.8]","[0.0, 2.7, 19.4]","[62.4, 76.6, 93.4]","[0.0, 0.0, 0.0]","[11.5, 20.9, 36.0]","[28.8, 58.3, 79.2]","[38.0, 175.5, 314.5]","[17.0, 60.1, 100.0]"
3,2023-09-04,['rain'],06:07:38,19:26:00,"[11.1, 19.3, 26.3]","[6.3, 10.8, 16.2]","[2.8, 19.3, 26.3]","[0.0, 2.6, 13.5]","[65.4, 77.6, 92.8]","[0.0, 0.0, 0.0]","[10.8, 20.5, 36.7]","[39.6, 57.2, 90.0]","[43.3, 189.0, 288.3]","[8.3, 60.7, 100.0]"
4,2023-09-05,NaN,06:09:06,19:23:53,"[7.7, 19.4, 27.4]","[3.4, 10.6, 14.7]","[-3.5, 19.4, 27.2]","[0.0, 2.7, 32.1]","[66.7, 77.5, 91.3]","[0.0, 0.0, 0.0]","[9.0, 22.0, 50.4]","[43.2, 63.0, 100.8]","[33.8, 157.0, 269.7]","[21.0, 55.9, 94.3]"
5,2023-09-06,NaN,06:10:33,19:21:45,"[12.7, 18.7, 27.1]","[3.2, 9.4, 14.7]","[0.9, 18.7, 27.1]","[0.0, 5.3, 49.9]","[67.1, 78.5, 96.8]","[0.0, 0.0, 0.0]","[11.5, 20.2, 36.7]","[43.2, 56.5, 97.2]","[35.0, 178.1, 259.9]","[11.3, 56.4, 100.0]"

In [276]:
df_weather_forecast.shape,df_weather.shape

((15, 36), (669, 38))

In [277]:
common_columns = set(df_weather.columns).intersection(set(df_weather_forecast.columns))
common_columns

{'cloudcover',
 'datetime',
 'dew',
 'feelslike',
 'feelslikemax',
 'feelslikemin',
 'humidity',
 'precip',
 'precipcover',
 'preciptype',
 'pressure',
 'snow',
 'snowdepth',
 'solarenergy',
 'solarradiation',
 'sunrise',
 'sunset',
 'temp',
 'tempmax',
 'tempmin',
 'uvindex',
 'visibility',
 'winddir',
 'windgust',
 'windspeed'}

In [278]:
df_weather[list(common_columns)].dtypes

winddir           float64
feelslikemin      float64
dew               float64
windgust          float64
precipcover       float64
uvindex           float64
snow              float64
sunset             object
solarenergy       float64
visibility        float64
precip            float64
pressure          float64
tempmin           float64
preciptype         object
cloudcover        float64
datetime           object
sunrise            object
tempmax           float64
windspeed         float64
feelslikemax      float64
temp              float64
feelslike         float64
solarradiation    float64
humidity          float64
snowdepth         float64
dtype: object

In [279]:
df_weather['preciptype'].unique()

array(["['rain']", nan, "['rain', 'snow']", "['snow']"], dtype=object)

# 2. Feature Engineering

## 2.1 SEMS Solar Data

In [280]:
df_solar.columns

Index(['Datum', 'Elektrárna', 'Klasifikace', 'Kapacita(kW)', 'PV(kWh)',
       'Prodej(kWh)', 'Koupit(kWh)', 'Spotřeba(kWh)',
       'Spotřebováno v domácnosti(kWh)', 'Vlastní poměr(%)',
       'Contribution Ratio(%)', 'Příjem(CZK)'],
      dtype='object')

In [281]:
df_solar_data = df_solar[['Datum','PV(kWh)']].copy()

In [282]:
df_solar_data

          Datum  PV(kWh)
0    01.01.2024      1.2
1    02.01.2024      1.3
2    03.01.2024      1.9
3    04.01.2024      1.8
4    05.01.2024      4.5
..          ...      ...
664  27.12.2024     13.3
665  28.12.2024     11.0
666  29.12.2024     14.2
667  30.12.2024     13.1
668  31.12.2024      4.9

[669 rows x 2 columns]

In [283]:
df_solar_data.dtypes

Datum       object
PV(kWh)    float64
dtype: object

In [284]:
df_solar_data['Datum'] = df_solar_data['Datum'].str.replace(r'\.', '-', regex=True)
df_solar_data['Datum'] = pd.to_datetime(df_solar_data['Datum'], dayfirst=True)
df_solar_data

         Datum  PV(kWh)
0   2024-01-01      1.2
1   2024-01-02      1.3
2   2024-01-03      1.9
3   2024-01-04      1.8
4   2024-01-05      4.5
..         ...      ...
664 2024-12-27     13.3
665 2024-12-28     11.0
666 2024-12-29     14.2
667 2024-12-30     13.1
668 2024-12-31      4.9

[669 rows x 2 columns]

In [285]:
df_solar_data['month'] = df_solar_data['Datum'].dt.month
df_solar_data['dayofyear'] = df_solar_data['Datum'].dt.dayofyear

df_solar_data['sin_month'] = np.sin(2 * np.pi * df_solar_data['month'] / 12)
df_solar_data['cos_month'] = np.cos(2 * np.pi * df_solar_data['month'] / 12)


df_solar_data['sin_dayofyear'] = np.sin(2 * np.pi * df_solar_data['dayofyear'] / 365)
df_solar_data['cos_dayofyear'] = np.cos(2 * np.pi * df_solar_data['dayofyear'] / 365)

df_solar_data['year'] = df_solar_data['Datum'].dt.year

In [286]:
df_solar_data.head(5)

,Datum,PV(kWh),month,dayofyear,sin_month,cos_month,sin_dayofyear,cos_dayofyear,year
0,2024-01-01,1.2,1,1,0.5,0.866025,0.017213,0.999852,2024
1,2024-01-02,1.3,1,2,0.5,0.866025,0.034422,0.999407,2024
2,2024-01-03,1.9,1,3,0.5,0.866025,0.051620,0.998667,2024
3,2024-01-04,1.8,1,4,0.5,0.866025,0.068802,0.997630,2024
4,2024-01-05,4.5,1,5,0.5,0.866025,0.085965,0.996298,2024

In [287]:
df_solar_data_final = df_solar_data.drop(columns=['month', 'dayofyear'])

In [288]:
df_solar_data_final.head(5)

,Datum,PV(kWh),sin_month,cos_month,sin_dayofyear,cos_dayofyear,year
0,2024-01-01,1.2,0.5,0.866025,0.017213,0.999852,2024
1,2024-01-02,1.3,0.5,0.866025,0.034422,0.999407,2024
2,2024-01-03,1.9,0.5,0.866025,0.051620,0.998667,2024
3,2024-01-04,1.8,0.5,0.866025,0.068802,0.997630,2024
4,2024-01-05,4.5,0.5,0.866025,0.085965,0.996298,2024

## 2.2 Weather Data

In [289]:
df_weather_data = df_weather[list(common_columns)].copy()
df_weather_data.head(5)

,winddir,feelslikemin,dew,windgust,precipcover,uvindex,snow,sunset,solarenergy,visibility,...,datetime,sunrise,tempmax,windspeed,feelslikemax,temp,feelslike,solarradiation,humidity,snowdepth
0,218.2,8.3,10.4,46.8,4.17,5.0,0.0,19:32:17,11.0,33.9,...,2023-09-01,06:03:16,18.1,20.8,18.1,14.3,14.2,127.9,77.7,0.0
1,286.5,15.0,14.2,43.2,8.33,8.0,0.0,19:30:12,18.2,36.1,...,2023-09-02,06:04:44,21.3,12.9,21.3,17.7,17.7,209.2,81.1,0.0
2,344.2,14.3,12.6,50.4,16.67,10.0,0.0,19:28:06,15.2,29.0,...,2023-09-03,06:06:11,19.2,15.4,19.2,16.3,16.3,175.2,79.9,0.0
3,14.2,11.9,9.9,54.0,4.17,7.0,0.0,19:26:00,14.9,31.7,...,2023-09-04,06:07:38,18.5,17.6,18.5,14.7,14.7,171.2,73.9,0.0
4,59.9,7.9,9.9,43.2,0.00,7.0,0.0,19:23:53,20.6,31.6,...,2023-09-05,06:09:06,24.2,12.2,24.2,15.7,15.4,239.3,71.2,0.0

In [290]:
df_weather_data.select_dtypes('object')

       sunset preciptype    datetime   sunrise
0    19:32:17   ['rain']  2023-09-01  06:03:16
1    19:30:12   ['rain']  2023-09-02  06:04:44
2    19:28:06   ['rain']  2023-09-03  06:06:11
3    19:26:00   ['rain']  2023-09-04  06:07:38
4    19:23:53        NaN  2023-09-05  06:09:06
..        ...        ...         ...       ...
664  20:58:50   ['rain']  2025-06-26  04:43:14
665  20:58:46   ['rain']  2025-06-27  04:43:42
666  20:58:38        NaN  2025-06-28  04:44:11
667  20:58:28        NaN  2025-06-29  04:44:44
668  20:58:16        NaN  2025-06-30  04:45:19

[669 rows x 4 columns]

In [291]:
df_weather_data['datetime'] = pd.to_datetime(df_weather_data['datetime'])

In [292]:
df_weather_data['month'] = df_weather_data['datetime'].dt.month
df_weather_data['dayofyear'] = df_weather_data['datetime'].dt.dayofyear

df_weather_data['sin_month'] = np.sin(2 * np.pi * df_weather_data['month'] / 12)
df_weather_data['cos_month'] = np.cos(2 * np.pi * df_weather_data['month'] / 12)


df_weather_data['sin_dayofyear'] = np.sin(2 * np.pi * df_weather_data['dayofyear'] / 365)
df_weather_data['cos_dayofyear'] = np.cos(2 * np.pi * df_weather_data['dayofyear'] / 365)

df_weather_data['year'] = df_weather_data['datetime'].dt.year

In [293]:
def time_to_seconds(t):
    """Převede časový string HH:MM:SS na počet sekund od půlnoci."""
    h, m, s = map(int, t.split(':'))
    return h*3600 + m*60 + s


df_weather_data['sunset_seconds'] = df_weather_data['sunset'].apply(time_to_seconds)
df_weather_data['sunrise_seconds'] = df_weather_data['sunrise'].apply(time_to_seconds)


seconds_in_day = 24*3600
df_weather_data['sunset_sin'] = np.sin(2 * np.pi * df_weather_data['sunset_seconds'] / seconds_in_day)
df_weather_data['sunset_cos'] = np.cos(2 * np.pi * df_weather_data['sunset_seconds'] / seconds_in_day)


df_weather_data['sunrise_sin'] = np.sin(2 * np.pi * df_weather_data['sunrise_seconds'] / seconds_in_day)
df_weather_data['sunrise_cos'] = np.cos(2 * np.pi * df_weather_data['sunrise_seconds'] / seconds_in_day)


df_weather_data['day_length_seconds'] = df_weather_data['sunset_seconds'] - df_weather_data['sunrise_seconds']


df_weather_data['day_length_hours'] = df_weather_data['day_length_seconds'] / 3600

In [294]:
df_weather_data['preciptype']= df_weather_data['preciptype'].fillna("['none']")
df_weather_data['preciptype'].value_counts()

preciptype
['rain']            287
['none']            255
['rain', 'snow']    110
['snow']             17
Name: count, dtype: int64

In [295]:
df_weather_data.columns

Index(['winddir', 'feelslikemin', 'dew', 'windgust', 'precipcover', 'uvindex',
       'snow', 'sunset', 'solarenergy', 'visibility', 'precip', 'pressure',
       'tempmin', 'preciptype', 'cloudcover', 'datetime', 'sunrise', 'tempmax',
       'windspeed', 'feelslikemax', 'temp', 'feelslike', 'solarradiation',
       'humidity', 'snowdepth', 'month', 'dayofyear', 'sin_month', 'cos_month',
       'sin_dayofyear', 'cos_dayofyear', 'year', 'sunset_seconds',
       'sunrise_seconds', 'sunset_sin', 'sunset_cos', 'sunrise_sin',
       'sunrise_cos', 'day_length_seconds', 'day_length_hours'],
      dtype='object')

In [296]:
df_weather_data_final = df_weather_data.drop(columns=[ 'sunset', 'sunrise', 'month', 'dayofyear'])

In [301]:
df_final = pd.merge(df_solar_data_final, df_weather_data_final, left_on='Datum',right_on=  'datetime', how='inner')

In [302]:
df_final

,Datum,PV(kWh),sin_month_x,cos_month_x,sin_dayofyear_x,cos_dayofyear_x,year_x,winddir,feelslikemin,dew,...,cos_dayofyear_y,year_y,sunset_seconds,sunrise_seconds,sunset_sin,sunset_cos,sunrise_sin,sunrise_cos,day_length_seconds,day_length_hours
0,2024-01-01,1.2,5.000000e-01,0.866025,1.721336e-02,0.999852,2024,243.4,-1.9,1.7,...,0.999852,2024,57521,27866,-0.863139,-0.504967,0.897964,-0.440070,29655,8.237500
1,2024-01-02,1.3,5.000000e-01,0.866025,3.442161e-02,0.999407,2024,202.9,-3.2,0.2,...,0.999407,2024,57581,27863,-0.865334,-0.501196,0.898060,-0.439874,29718,8.255000
2,2024-01-03,1.9,5.000000e-01,0.866025,5.161967e-02,0.998667,2024,221.7,-0.7,3.7,...,0.998667,2024,57644,27857,-0.867621,-0.497226,0.898251,-0.439482,29787,8.274167
3,2024-01-04,1.8,5.000000e-01,0.866025,6.880243e-02,0.997630,2024,246.0,-1.1,2.9,...,0.997630,2024,57709,27848,-0.869962,-0.493120,0.898539,-0.438894,29861,8.294722
4,2024-01-05,4.5,5.000000e-01,0.866025,8.596480e-02,0.996298,2024,203.1,-3.4,0.9,...,0.996298,2024,57776,27836,-0.872354,-0.488875,0.898922,-0.438110,29940,8.316667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
664,2024-12-27,13.3,-2.449294e-16,1.000000,-5.161967e-02,0.998667,2024,46.5,-8.5,-7.6,...,0.998667,2024,57295,27843,-0.854723,-0.519084,0.898698,-0.438567,29452,8.181111
665,2024-12-28,11.0,-2.449294e-16,1.000000,-3.442161e-02,0.999407,2024,67.1,-3.7,-2.9,...,0.999407,2024,57345,27853,-0.856605,-0.515973,0.898379,-0.439221,29492,8.192222
666,2024-12-29,14.2,-2.449294e-16,1.000000,-1.721336e-02,0.999852,2024,256.2,-6.8,-4.5,...,0.999852,2024,57396,27861,-0.858513,-0.512792,0.898124,-0.439743,29535,8.204167
667,2024-12-30,13.1,-2.449294e-16,1.000000,6.432491e-16,1.000000,2024,257.1,-8.7,-4.3,...,1.000000,2024,57451,27865,-0.860557,-0.509354,0.897996,-0.440004,29586,8.218333
668,2024-12-31,4.9,-2.449294e-16,1.000000,1.721336e-02,0.999852,2024,224.7,-9.8,-4.8,...,0.999852,2024,57508,27866,-0.862661,-0.505783,0.897964,-0.440070,29642,8.233889

In [ ]:
df_final.to_csv('Model/data_model.csv', index=False)